"""Added order and product tables

Revision ID: 2a65839f7830
Revises: 
Create Date: 2024-03-03 15:28:33.615163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a65839f7830'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('contractor', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Float(precision=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('quantity', sa.String(length=3), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('price', sa.Float(precision=2), nullable=False),
    sa.Column('amount', sa.Float(precision=2), nullable=False),
    sa.Column('order_id', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    op.drop_table('order')
    # ### end Alembic commands ###
